#!/bin/sh

ffmpeg -framerate `cat ../framerate` -i "deactivate frame %d.png" -filter_complex "[0:v] split [a][b]; [a] palettegen=reserve_transparent=on:transparency_color=d3d3d3 [p];[b][p] paletteuse" -loop -1 deactivate.gif
